#!/usr/bin/lua

--[[
TODO:
  - Set up handling for all events wew sends and nil, even if they're just a return.
  - Window focus on mouse enter event? (7)
  - Manage the windows in a stack with chwso; when mouse enters, a window should maybe gain temporary focus, but only for mouse events like clicking and scrolling—though scrolling may work without focus, which would be nice. The window that *had* focus prior to the mouse entry should regain focus on keyboard events, perhaps?
  - Fancy border colours! I think the border on the (main) focused window should be bigger.
  - user defined grid, like parking spaces, with padding. Programs can have reserved spaces, and anything else will get out of their way. Windows that have defined spaces will automatically go to them, programs that don't may be left floating or find an unoccupied space. Should be able to be different per virtual desktop
--]]

local border_active = {"800080", "4"}
local border_inactive = {"008080", "4"}

local function activate(wid)
    os.execute("wtf "..wid)
    os.execute("chwso -r "..wid)
    os.execute("chwb -c "..border_active[1].." -s "..border_active[2].." "..wid)
end

local function deactivate(wid)
    os.execute("chwb -c "..border_inactive[1].." -s "..border_inactive[2].." "..wid)
end

--Event Listener Thing
local function listen(filename)
    --This is a gross way to make sure the file is empty. I'm sure there's a better way...
    os.execute("echo -n > "..filename)
    --"wew -m 524336" shows enter + leaving windows, and creation/destruction events. Add the numbers from "wew -l" together to get the combos you want!
    --Right now, I'mma put this in .xinitrc, because I'm ending up with dozens of wews running since I'm restarting this sooooo often XD
    --Eventually, this could probably start it.
    --os.execute("wew -m 524336 >> "..filename.."&")
    return io.open(filename, "r+")
end

m_events = listen("m_events")
--Okay, *now* I should be able to send other events! This should also make the loop tighter, as it's not waiting on wew. Dunno what that'll do to the resources being used, though :O

--temp!
m_events = io.popen("wew -m 524336")

while true do
    local event = m_events:read("*l")
    --if event ~= nil then
        local colon = event:find(":")
        local value = event:sub(1, colon-1)
        local wid = event:sub(colon+1)
        print(event)
        -- New window is created
        if value == "16" then
            activate(wid)
        elseif value == "7" then
            activate(wid)
        elseif value == "8" then
            deactivate(wid)
        end
    --end
end
